name: ci

on: [push, pull_request]

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -e .[tests,lint]
    - run: flake8
    - run: mypy .
